### ISSUE TITLE
document operator precedence

### ISSUE THREAD

**Issue by mauhiz** [NET-A-PORTER/scala-uri#48]
a uri defined with the dsl can lead to surprising results :

```scala
scala> "http://host" / "path" / "to" / "resource" ? ("a" -> "1" ) & ("b" -> "2")
res1: com.netaporter.uri.Uri = http://host/path/to/%2Fresource%3Fa%3D1?b=2
```

As I understand it this is because of Scala operator precedence : & then / then ?
and because the & operator is not defined for Tuple2, even with the dsl.

From there two options : 
* expose more implicit conversions/operators
* document this shortcoming and a simple fix like :
```scala
scala> ("http://host" / "path" / "to" / "resource") ? ("a" -> "1" ) & ("b" -> "2")
res2: com.netaporter.uri.Uri = http://host/path/to/resource?a=1&b=2
```

**Comment by theon** [comment]
This has now been properly fixed in `0.4.10-SNAPSHOT`:

```scala
"http://host" / "path" / "to" / "resource" ? ("a" -> "1" ) & ("b" -> "2")
res0: com.netaporter.uri.Uri = http://host/path/to/resource?a=1&b=2
```
