### ISSUE TITLE
Support jdbc URLs

### ISSUE THREAD

**Issue by electricmonk** [NET-A-PORTER/scala-uri#49]
When parsing a JDBC url:
```scala
Uri.parse("jdbc:mysql://localhost:3306/some_db")
```

it is being parsed as a relative url. This is because in `UrlParser`, the `_scheme` rule expects the scheme part to be alphanumeric.

Ideally, you could relax the parser a bit to allow for colons, thus supporting JDBC urls as well.

**Comment by rathboma** [comment]
Ah, we just ran into this same issue also. Would be great to include JDBC url support.

**Comment by philwill-nap** [comment]
My opinion, after looking at [some sample](http://www.herongyang.com/JDBC/Oracle-JDBC-Driver-Connection-URL.html) JDBC connection "URL"s is that they are not suitable for parsing with this library as they are not *at all* standardised.

You could build a library to do it, it would need to recognise the "jdbc:" prefix then delegate the rest of the parsing to the parser that matches the next prefix (e.g. "oracle:" or other vendors) which may again need to delegate to a different parser for the next prefix (e.g. "thin:" or "oci:" for oracle) to comprehend the rest of the string.

The best thing to do is to stop calling them "URL" and start calling them "Connection string"

**Comment by theon** [comment]
@philwill-nap makes a good point. Closing this.
