### ISSUE TITLE
Conflict of shapeless version

### ISSUE THREAD

**Issue by lanarchyste** [NET-A-PORTER/scala-uri#53]
Hello,

I am currently working with Scala 2.10.3 and SBT 0.13.1.
My project contains most of the dependencies Spray 1.3.1.

When I add scala-uri to my project, I get an error in SBT: Conflicting cross-Version in suffixes: com.chuusai: shapeless

How to solve this problem?

Thanks.

**Comment by theon** [comment]
As mentioned [here in the spray docs](http://spray.io/project-info/current-versions/#shapeless-versions), specific versions of spray will only work with specific versions of shapeless. Not sure there is anything else I can do here to fix this.
