### ISSUE TITLE
Allow serializing empty keys to "key=" rather than "key"

### ISSUE THREAD

**Issue by svieira** [NET-A-PORTER/scala-uri#69]
In 0.4.3:

```scala
val uri_string = "https://a.domain.here?a=1&b=&c="
uri_string ? ("d", "")
```

results in:

```scala
res3: com.netaporter.uri.Uri = https://a.domain.here?a=1&b&c&d
```

Ideally, it would be possible to specify that the desired serialization is:

```scala
res3: com.netaporter.uri.Uri = https://a.domain.here?a=1&b=&c=&d=
```

Nothing is specified about this in [RFC 3986](http://tools.ietf.org/html/rfc3986), but the [HTML5 form section regarding application/x-www-form-urlencoded encoding](http://www.w3.org/TR/html5/forms.html#url-encoded-form-data) has this to say about the encoding steps:

> 8. If this is not the first entry, append a single U+0026 AMPERSAND character (&) to result.
> 9. Append the entry's name to result.
> 10. Append a single "=" (U+003D) character to result.
> 11. Append the entry's value to result.

This change was introduced in 9e20420d6452c533a98bd9e6b507133be3643557 (more specifically, [this change to Parameters.scala](https://github.com/NET-A-PORTER/scala-uri/commit/9e20420d6452c533a98bd9e6b507133be3643557#diff-30fada1638430656cb4a942afa5364ccL140))

**Comment by theon** [comment]
Should be fixed in #76
