### ISSUE TITLE
Incorrect result when adding a query string parameter to a URL string containing an at sign in another query string parameter

### ISSUE THREAD

**Issue by balihoo-mrogers** [NET-A-PORTER/scala-uri#72]
I'm using scala-uri 0.4.3.

This works correctly:
scala> "http://hello.world?email=abc" ? ("this", "that")
res38: com.netaporter.uri.Uri = http://hello.world?email=abc&this=that

But when the first query string parameter has an at sign in it, the second parameter is appended using a question mark instead of an ampersand:
scala> "http://hello.world?email=abc@xyz" ? ("this", "that")
res39: com.netaporter.uri.Uri = http://hello.world?email=abc@xyz?this=that

**Comment by theon** [comment]
Thanks for raising this @balihoo-mrogers and sorry for taking so long to reply.

This should be fixed now as of 42d5baf228822a6291c823d1258e9d6e5b7b40cb

**Comment by balihoo-mrogers** [comment]
Thanks for fixing it!
