### ISSUE TITLE
User info should be percent encoded

### ISSUE THREAD

**Issue by balihoo-mrogers** [NET-A-PORTER/scala-uri#73]
The username and password in a URL should be precent encoded.

Here's what I get when I try it in the current version:
scala> "http://somwhere.something".withUser("user:1@domain").withPassword("abc xyz")
res9: com.netaporter.uri.Uri = http://user:1@domain:abc xyz@somwhere.something

**Comment by theon** [comment]
Good shout. I will look to add this in.

**Comment by theon** [comment]
Sorry about the year and a half delay..... fixed now :smile:

**Comment by balihoo-mrogers** [comment]
Thank you!

On Thu, Mar 31, 2016 at 2:58 AM, Ian Forsey <notifications@github.com>
wrote:

> Sorry about the year and a half delay..... fixed now [image: :smile:]
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/NET-A-PORTER/scala-uri/issues/73#issuecomment-203833082>
>



-- 
*Mark Rogers*
*Balihoo | Senior Software Engineer*
404 S. 8th St Ste 300
Boise, ID 83702
balihoo.com

<http://balihoo.com/>
