### ISSUE TITLE
Can the `/` operator squash multiple slashes?

### ISSUE THREAD

**Issue by acjay** [NET-A-PORTER/scala-uri#80]
In cases where a base URI is provide with a slash, should the `/` operator not duplicate the slash? I can see the counterargument that right now, it very explicitly inserts a slash, always. I appreciate the consistency, but I'd suggest it might actually be "least surprise" to squash slashes adjacent to the `/` operator.

**Comment by philwill-nap** [comment]
`http://example.com/fred` and `http://example.com//fred` are both legal URIs identifying distinct resources; to coalesce adjacent `/` characters it would be incorrect.

**Comment by larioj** [comment]
Say we wanted the squashing behavior. What operator should we use?

**Comment by xkrt** [comment]
Additional `squashing /` operator will be very convenient
