### ISSUE TITLE
Is scala-uri RFC 3986 compliant?

### ISSUE THREAD

**Issue by wsargent** [NET-A-PORTER/scala-uri#81]
I didn't see a mailing list link, so apologies if this is an obvious question: does scala-uri parse URIs in an RFC-3986 compliant fashion, so that parsing a URL is different for each part of the URL and properly handles the different reserved characters?

I know that https://github.com/palominolabs/url-builder is an option, but I'd rather use scala-uri because the DSL is so much nicer.

Also blog posts:

http://blog.lunatech.com/2009/02/03/what-every-web-developer-must-know-about-url-encoding
http://blog.palominolabs.com/2013/10/03/creating-urls-correctly-and-safely/

**Comment by philwill-nap** [comment]
If you find that it isn't, we consider that a defect.

**Comment by wsargent** [comment]
On a similar note, does scala-uri support URL normalization? https://en.wikipedia.org/wiki/URL_normalization

**Comment by philwill-nap** [comment]
No; this belongs in a layer above, at least until everyone agrees what that means and preferably until it is a formal part of the URI specification.
