### ISSUE TITLE
How do I remove a protocol / scheme from a URI?

### ISSUE THREAD

**Issue by wsargent** [NET-A-PORTER/scala-uri#82]
I'd like to create a protocol relative URL from an absolute URL, but I don't see a way to do that from the documentation.  Is this possible?

**Comment by philwill-nap** [comment]
Try this in the REPL:

    import com.netaporter.uri._
    val absoluteUri = Uri.parse("scheme://host/path")
    val protocolRelativeUri = absoluteUri.copy(scheme=None)
