### ISSUE TITLE
Equals-signs in URI fragment are unnecessarily escaped

### ISSUE THREAD

**Issue by JustAHappyKid** [NET-A-PORTER/scala-uri#97]
E.g., `Uri.parse("https://test.com/page#this=that").toString` yields string value `https://test.com/page#this%3Dthat`. According to [this StackOverflow post](https://stackoverflow.com/questions/2849756/) (which is according to RFC 3986), equals (along with many other characters) is allowed in the fragment unmolested (not percent-encoded).

Happy to try to whip up a test-case and/or patch... but punting for now since it's late. :-)

**Comment by theon** [comment]
Should be fixed in `0.4.11`. I committed the fix against #99
